import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cluster pairs dataset generated by your script
PAIRS_FILE = 'redmapper_cluster_pairs_angular.csv'
df = pd.read_csv(PAIRS_FILE)

# Compute mean properties 
df['z_mean'] = (df['z_L'] + df['z_R']) / 2.0
df['lam_mean'] = (df['lam_L'] + df['lam_R']) / 2.0

# Define clean raw strings for labels to avoid mathtext parsing errors
x_var = df['z_mean']
y_var = df['lam_mean']
z_var = df['sep_rad']

labels = [
    r'Mean Redshift ($\langle z \rangle$)', 
    r'Mean Richness ($\langle \lambda \rangle$)', 
    r'Separation ($\theta_{\text{sep}}$ [rad])'
]
data_columns = [x_var, y_var, z_var]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

pairs = [
    (0, 1), # Mean Redshift vs Mean Richness
    (0, 2), # Mean Redshift vs Separation
    (1, 2)  # Mean Richness vs Separation
]

for ax, (i, j) in zip(axes, pairs):
    sns.histplot(
        x=data_columns[i], 
        y=data_columns[j], 
        ax=ax, 
        cmap='viridis', 
        cbar=True, 
        bins=30
    )
    
    ax.set_xlabel(labels[i], fontsize=12)
    ax.set_ylabel(labels[j], fontsize=12)
    ax.set_title(f'{labels[i]} vs {labels[j]}', fontsize=14)

plt.tight_layout()
plt.savefig('filaments/joint_distributions_pair_props_ANG.png', dpi=300)
plt.show()
